graphhopper:
  # OpenStreetMap input file
  datareader.file: "turkey-latest.osm.pbf"
  # Local folder used by graphhopper to store its data
  graph.location: "turkey-graph-cache"

  # Traffic-aware routing configuration
  traffic:
    api:
      url: "https://api.metasyon.com/eds_data"
    # EDS data API enabled for real-time traffic data
    auto_start: true

  # Custom areas configuration (road works, excavation works, etc.)
  custom_areas:
    enabled: true
    api:
      url: "http://20.199.11.220:9000/custom-areas"  # 6 saatte bir çekilecek
      update_interval_hours: 6

  # Routing Profiles
  profiles:
    - name: car
      weighting: custom
      custom_model_files: [car.json]
    - name: foot
      weighting: custom
      custom_model_files: [foot_custom.json]
    - name: bike
      weighting: custom
      custom_model_files: [bike_custom.json]

  # Disable CH and LM for traffic-aware routing
  profiles_ch: []
  profiles_lm: []
  

  # Encoded values for car, bike and foot routing
  graph.encoded_values: car_access, car_average_speed, road_class, road_access, bike_priority, bike_access, roundabout, bike_average_speed, bike_road_access, foot_road_access, average_slope, mtb_rating, hike_rating, country, foot_access, foot_priority, foot_average_speed, road_environment

  # Performance settings
  graph.dataaccess.default_type: RAM_STORE
  graph.dataaccess.segment_size: 16777216
  prepare.min_network_size: 200
  prepare.subnetworks.threads: 1
  routing.max_visited_nodes: 2000000
  routing.snap_preventions_default: tunnel, bridge, ferry
  routing.timeout_ms: 300000
  routing.non_ch.max_waypoint_distance: 1000000

  # Exclude non-car highways (but keep foot and bike paths)
  import.osm.ignored_highways: construction,bridleway

  # Turkish language preference
  datareader.preferred_language: tr

# Server configuration
server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
      max_request_header_size: 50k
  request_log:
    appenders: []
  admin_connectors:
    - type: http
      port: 8990
      bind_host: localhost

# Logging configuration
logging:
  appenders:
    - type: file
      time_zone: UTC
      current_log_filename: logs/graphhopper.log
      log_format: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
      archive: true
      archived_log_filename_pattern: ./logs/graphhopper-%d.log.gz
      archived_file_count: 30
      never_block: true
    - type: console
      time_zone: UTC
      log_format: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  loggers:
    "com.graphhopper.traffic":
      level: DEBUG
      additive: true
    "com.graphhopper.osm_warnings":
      level: DEBUG
      additive: false
      appenders:
        - type: file
          currentLogFilename: logs/osm_warnings.log
          archive: false
          logFormat: '[%level] %msg%n'