# Docker Compose version is now optional

services:
  graphhopper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphhopper-app
    ports:
      - "8989:8989"
      - "8990:8990"
    volumes:
      - ./turkey-graph-cache:/app/turkey-graph-cache
      - ./logs:/app/logs
    environment:
      - JAVA_OPTS=-Xmx4g -Xms1g -XX:+UseG1GC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s 